In [ ]:
import pandas as pd

In [ ]:
df= pd.read_csv('/content/drive/MyDrive/datasets/data.csv')
df.head()

,Player,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
0,Cristiano Ronaldo,02/03,Liga Portugal,6,2002-10-07,H,Sporting CP,Moreirense FC,3:00,LW,34,2:00,Solo run,NaN
1,Cristiano Ronaldo,02/03,Liga Portugal,6,2002-10-07,H,Sporting CP,Moreirense FC,3:00,LW,90+5,3:00,Header,Rui Jorge
2,Cristiano Ronaldo,02/03,Liga Portugal,8,2002-10-26,A,Sporting CP,Boavista FC,1:02,NaN,88,1:02,Right-footed shot,Carlos Martins
3,Cristiano Ronaldo,02/03,Taca de Portugal Placard,Fourth Round,2002-11-24,H,Sporting CP,CD Estarreja,4:01,NaN,67,3:00,Left-footed shot,Cesar Prates
4,Cristiano Ronaldo,02/03,Taca de Portugal Placard,Fifth Round,2002-12-18,H,Sporting CP,FC Oliveira do Hospital,8:01,NaN,13,3:00,NaN,NaN

Using the dataset, answer the folllowing questions:

- How many goals are in the dataset in total.
- How many goals have the two players each scored
- which are the columns in the dataset
- what are the data types of each column? How many are they
- How much memory is the dataset consuming?
- How many null values do we have in each column

In [ ]:
df.shape[0]

1413

In [ ]:
cr_df = df[df["Player"]=="Cristiano Ronaldo"]
lm_df= df[df["Player"]=="Lionel Messi"]
print(f"Cristiano Ronaldo scored {cr_df.shape[0]} goals")
print(f"Lionel Messi scored {lm_df.shape[0]} goals")

Cristiano Ronaldo scored 710 goals
Lionel Messi scored 703 goals

In [ ]:
df.columns

Index(['Player', 'Season', 'Competition', 'Matchday', 'Date', 'Venue', 'Club',
       'Opponent', 'Result', 'Playing_Position', 'Minute', 'At_score', 'Type',
       'Goal_assist'],
      dtype='object')

In [ ]:
len(df.columns)

14

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1413 entries, 0 to 1412
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Player            1413 non-null   object
 1   Season            1413 non-null   object
 2   Competition       1413 non-null   object
 3   Matchday          1413 non-null   object
 4   Date              1413 non-null   object
 5   Venue             1413 non-null   object
 6   Club              1413 non-null   object
 7   Opponent          1413 non-null   object
 8   Result            1413 non-null   object
 9   Playing_Position  1355 non-null   object
 10  Minute            1413 non-null   object
 11  At_score          1413 non-null   object
 12  Type              1397 non-null   object
 13  Goal_assist       953 non-null    object
dtypes: object(14)
memory usage: 154.7+ KB

In [ ]:
df.isna().sum()

Player                0
Season                0
Competition           0
Matchday              0
Date                  0
Venue                 0
Club                  0
Opponent              0
Result                0
Playing_Position     58
Minute                0
At_score              0
Type                 16
Goal_assist         460
dtype: int64

Season

In [ ]:
df["Season"].unique()

array(['02/03', '03/04', '04/05', '05/06', '06/07', '07/08', '08/09',
       '09/10', '10/11', '11-Dec', '11/12', 'Dec-13', '13/14', '14/15',
       '15/16', '16/17', '17/18', '18/19', '19/20', '20/21', '21/22',
       '22/23'], dtype=object)

How do we clean?

What do we replace the 2 values (11-dec and Dec-13) with

In [ ]:
df[df["Season"] == "11-Dec"].head()

,Player,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
389,Lionel Messi,11-Dec,Supercopa,final,2011-08-14,A,FC Barcelona,Real Madrid,2:02,CF,45,1:02,Left-footed shot,Thiago
390,Lionel Messi,11-Dec,Supercopa,final,2011-08-17,H,FC Barcelona,Real Madrid,3:02,CF,88,3:02,Left-footed shot,Adriano
391,Lionel Messi,11-Dec,Supercopa,final,2011-08-17,H,FC Barcelona,Real Madrid,3:02,CF,44,2:01,Right-footed shot,Gerard Pique
393,Lionel Messi,11-Dec,UEFA Super Cup,Final,2011-08-26,H,FC Barcelona,FC Porto,2:00,CF,39,1:00,Left-footed shot,NaN
397,Lionel Messi,11-Dec,LaLiga,2,2011-08-29,H,FC Barcelona,Villarreal CF,5:00,CF,74,5:00,Left-footed shot,Thiago

In [ ]:
df[df["Season"] == "Dec-13"].head()

,Player,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
522,Lionel Messi,Dec-13,LaLiga,1,2012-08-19,H,FC Barcelona,Real Sociedad,5:01,CF,10,2:01,Left-footed shot,Pedro
523,Lionel Messi,Dec-13,LaLiga,1,2012-08-19,H,FC Barcelona,Real Sociedad,5:01,CF,15,3:01,Left-footed shot,Cristian Tello
524,Lionel Messi,Dec-13,Supercopa,final,2012-08-23,H,FC Barcelona,Real Madrid,3:02,CF,60,2:01,Penalty,NaN
525,Cristiano Ronaldo,Dec-13,Supercopa,final,2012-08-23,A,Real Madrid,FC Barcelona,3:02,LW,55,0:01,Header,Mesut Ozil
526,Lionel Messi,Dec-13,LaLiga,2,2012-08-26,A,FC Barcelona,CA Osasuna,1:02,CF,74,1:01,Left-footed shot,Alexis Sanchez

.loc[ ] - condition and column to change

In [ ]:
df.loc[df["Season"]== "11-Dec", "Season" ] = "11/12"

In [ ]:
df.loc[df["Season"]== "Dec-13", "Season" ] = "12/13"

In [ ]:
df["Season"].unique()

array(['02/03', '03/04', '04/05', '05/06', '06/07', '07/08', '08/09',
       '09/10', '10/11', '11/12', '12/13', '13/14', '14/15', '15/16',
       '16/17', '17/18', '18/19', '19/20', '20/21', '21/22', '22/23'],
      dtype=object)

- how many unique seasons are now present in the dataset?
- what is the distribution of goals per season for the entire dataset?
- how many goals per season did each of the two players score?

In [ ]:
len(df["Season"].unique())

21

In [ ]:
df["Season"].value_counts()

Season
11/12    133
14/15    119
12/13    115
10/11    106
16/17     96
15/16     92
13/14     92
17/18     89
09/10     80
18/19     79
20/21     74
19/20     68
08/09     64
07/08     58
06/07     40
21/22     38
22/23     29
05/06     20
04/05     10
03/04      6
02/03      5
Name: count, dtype: int64

In [ ]:
df.groupby("Season")["Player"].value_counts()

Season  Player
02/03   Cristiano Ronaldo     5
03/04   Cristiano Ronaldo     6
04/05   Cristiano Ronaldo     9
        Lionel Messi          1
05/06   Cristiano Ronaldo    12
        Lionel Messi          8
06/07   Cristiano Ronaldo    23
        Lionel Messi         17
07/08   Cristiano Ronaldo    42
        Lionel Messi         16
08/09   Lionel Messi         38
        Cristiano Ronaldo    26
09/10   Lionel Messi         47
        Cristiano Ronaldo    33
10/11   Cristiano Ronaldo    53
        Lionel Messi         53
11/12   Lionel Messi         73
        Cristiano Ronaldo    60
12/13   Lionel Messi         60
        Cristiano Ronaldo    55
13/14   Cristiano Ronaldo    51
        Lionel Messi         41
14/15   Cristiano Ronaldo    61
        Lionel Messi         58
15/16   Cristiano Ronaldo    51
        Lionel Messi         41
16/17   Lionel Messi         54
        Cristiano Ronaldo    42
17/18   Lionel Messi         45
        Cristiano Ronaldo    44
18/19   Lionel Messi         51
        Cristiano Ronaldo    28
19/20   Cristiano Ronaldo    37
        Lionel Messi         31
20/21   Lionel Messi         38
        Cristiano Ronaldo    36
21/22   Cristiano Ronaldo    24
        Lionel Messi         14
22/23   Lionel Messi         17
        Cristiano Ronaldo    12
Name: count, dtype: int64

how many unique competitions are there in the dataset? Which ones are they? is there any that  need cleaning? if so clean them.

In [ ]:
df["Competition"].unique()

array(['Liga Portugal', 'Taca de Portugal Placard', 'Premier League',
       'FA Cup', 'LaLiga', 'UEFA Champions League Qualifying',
       'UEFA Champions League', 'EFL Cup', 'Copa del Rey',
       'FIFA Club World Cup', 'Supercopa', 'UEFA Super Cup', 'Serie A',
       'Supercoppa Italiana', 'Italy Cup', 'Ligue 1',
       'Troph�e des Champions', 'Trophée des Champions',
       'Champions League', 'Europa League', 'Saudi Pro League'],
      dtype=object)

In [ ]:
len(df["Competition"].unique())

21

In [ ]:
df.loc[df["Competition"]== "Troph�e des Champions", "Competition" ] = "Trophée des Champions"

In [ ]:
df.loc[df["Competition"]== "Champions League", "Competition" ] = "UEFA Champions League"

In [ ]:
df["Competition"].value_counts()

Competition
LaLiga                              785
UEFA Champions League               269
Premier League                      103
Serie A                              81
Copa del Rey                         78
Ligue 1                              20
Supercopa                            18
FA Cup                               13
FIFA Club World Cup                  12
Saudi Pro League                      9
UEFA Super Cup                        5
Italy Cup                             4
EFL Cup                               4
Liga Portugal                         3
Taca de Portugal Placard              2
Trophée des Champions                 2
Supercoppa Italiana                   2
Europa League                         2
UEFA Champions League Qualifying      1
Name: count, dtype: int64

After the above cleaning, generate insights on the following:
- How many unique competitions are there?
- Compare the goals scored by each of the players in the UEFA champions league and La Liga
- Compare the goals scored by each of the players in the league competition: i.e premire league, La Liga, Serie A, League 1, Saudi pro league, Liga Portugal (filtering)
- *How do the two players compare in the knock out stages of UEFA champions league - round of 16, quater finals, semi finals and finals

In [ ]:
len(df["Competition"].unique())

19

In [ ]:
ronaldo_champion = df[(df["Player"] == "Cristiano Ronaldo") & (df["Competition"] == "UEFA Champions League")]
messi_champion = df[(df["Player"] == "Lionel Messi") & (df["Competition"] == "UEFA Champions League")]
print(f"Cristiano Ronaldo scored {cr_df.shape[0]} goals")
print(f"Lionel Messi scored {lm_df.shape[0]} goals")

Cristiano Ronaldo scored 710 goals
Lionel Messi scored 703 goals

In [ ]:
df["Competition"].unique()

array(['Liga Portugal', 'Taca de Portugal Placard', 'Premier League',
       'FA Cup', 'LaLiga', 'UEFA Champions League Qualifying',
       'UEFA Champions League', 'EFL Cup', 'Copa del Rey',
       'FIFA Club World Cup', 'Supercopa', 'UEFA Super Cup', 'Serie A',
       'Supercoppa Italiana', 'Italy Cup', 'Ligue 1',
       'Trophée des Champions', 'Europa League', 'Saudi Pro League'],
      dtype=object)

In [ ]:
competitions = df[df["Competition"].isin(["Premier League", "LaLiga", "Serie A", "Ligue 1", "Saudi Pro League", "Liga Portugal"])]
competitions.head()

,Player,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
0,Cristiano Ronaldo,02/03,Liga Portugal,6,2002-10-07,H,Sporting CP,Moreirense FC,3:00,LW,34,2:00,Solo run,NaN
1,Cristiano Ronaldo,02/03,Liga Portugal,6,2002-10-07,H,Sporting CP,Moreirense FC,3:00,LW,90+5,3:00,Header,Rui Jorge
2,Cristiano Ronaldo,02/03,Liga Portugal,8,2002-10-26,A,Sporting CP,Boavista FC,1:02,NaN,88,1:02,Right-footed shot,Carlos Martins
5,Cristiano Ronaldo,03/04,Premier League,11,2003-11-01,H,Manchester United,Portsmouth FC,3:00,RW,80,2:00,Direct free kick,NaN
7,Cristiano Ronaldo,03/04,Premier League,29,2004-03-20,H,Manchester United,Tottenham Hotspur,3:00,NaN,89,2:00,Right-footed shot,NaN

In [ ]:
competitions.groupby(["Competition", "Player"])["Player"].count()

Competition       Player
LaLiga            Cristiano Ronaldo    311
                  Lionel Messi         474
Liga Portugal     Cristiano Ronaldo      3
Ligue 1           Lionel Messi          20
Premier League    Cristiano Ronaldo    103
Saudi Pro League  Cristiano Ronaldo      9
Serie A           Cristiano Ronaldo     81
Name: Player, dtype: int64

In [ ]:
df["Matchday"].unique()

array(['6', '8', 'Fourth Round', 'Fifth Round', '11', '29', '32', '38',
       'Final', '16', 'Third Round', '24', '25', 'Sixth Round', '30',
       'Semi-Finals', '34', '3rd round', 'Group Stage', '13',
       'Round of 16', '20', '19', '21', 'Quarter-Finals', '26', '28', '1',
       '2', '10', '15', '17', '23', '27', '6th round', '37', '35', '4',
       '5', '9', '7', '12', '18', '22', 'last 16', '31', '33', '3', '36',
       'final', '5th round', '4th round', '14'], dtype=object)

In [ ]:
cl = df[df["Competition"] == "UEFA Champions League"]
cl["Matchday"].unique()

array(['Group Stage', 'Quarter-Finals', 'Semi-Finals', 'last 16', 'Final'],
      dtype=object)

In [ ]:
knockout = cl[cl["Matchday"].isin(["last 16", "Quarter-Finals", "Semi-Finals", "Final"])]
knockout.head()

,Player,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
68,Cristiano Ronaldo,06/07,UEFA Champions League,Quarter-Finals,2007-04-10,H,Manchester United,AS Roma,7:01,RW,49,5:00,Right-footed shot,Ryan Giggs
69,Cristiano Ronaldo,06/07,UEFA Champions League,Quarter-Finals,2007-04-10,H,Manchester United,AS Roma,7:01,RW,44,4:00,Right-footed shot,Ryan Giggs
73,Cristiano Ronaldo,06/07,UEFA Champions League,Semi-Finals,2007-04-24,H,Manchester United,AC Milan,3:02,RW,5,1:00,Header,Ryan Giggs
120,Lionel Messi,07/08,UEFA Champions League,last 16,2008-02-20,A,FC Barcelona,Celtic FC,2:03,RW,18,1:01,Left-footed shot,Deco
121,Lionel Messi,07/08,UEFA Champions League,last 16,2008-02-20,A,FC Barcelona,Celtic FC,2:03,RW,79,2:03,Left-footed shot,NaN

In [ ]:
knockout.groupby(["Competition","Matchday", "Player"])["Player"].count()

Competition            Matchday        Player
UEFA Champions League  Final           Cristiano Ronaldo     4
                                       Lionel Messi          2
                       Quarter-Finals  Cristiano Ronaldo    25
                                       Lionel Messi         12
                       Semi-Finals     Cristiano Ronaldo    13
                                       Lionel Messi          6
                       last 16         Cristiano Ronaldo    25
                                       Lionel Messi         29
Name: Player, dtype: int64

In [ ]:
df.head()

,Player,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
0,Cristiano Ronaldo,02/03,Liga Portugal,6,2002-10-07,H,Sporting CP,Moreirense FC,3:00,LW,34,2:00,Solo run,NaN
1,Cristiano Ronaldo,02/03,Liga Portugal,6,2002-10-07,H,Sporting CP,Moreirense FC,3:00,LW,90+5,3:00,Header,Rui Jorge
2,Cristiano Ronaldo,02/03,Liga Portugal,8,2002-10-26,A,Sporting CP,Boavista FC,1:02,NaN,88,1:02,Right-footed shot,Carlos Martins
3,Cristiano Ronaldo,02/03,Taca de Portugal Placard,Fourth Round,2002-11-24,H,Sporting CP,CD Estarreja,4:01,NaN,67,3:00,Left-footed shot,Cesar Prates
4,Cristiano Ronaldo,02/03,Taca de Portugal Placard,Fifth Round,2002-12-18,H,Sporting CP,FC Oliveira do Hospital,8:01,NaN,13,3:00,NaN,NaN

how many games has each
 of the players scored in?

what is the scoring rate of the two players

In [ ]:
df.groupby("Player")["Date"].nunique().iloc

In [ ]:
goals_per_game = df.groupby("Player").agg(
    total_goals = ("Player", "count"),
    total_games = ("Date","nunique")

)
goals_per_game["goals_per_game"] = goals_per_game["total_goals"]/goals_per_game["total_games"]
goals_per_game

                   total_goals  total_games  goals_per_game
Player
Cristiano Ronaldo          710          468        1.517094
Lionel Messi               703          454        1.548458

What is the scoring rate for each of the two players per competition?

What is the scoring rate for each of thr two players per season?

In [ ]:
goals_per_competitions = df.groupby(["Player", "Competition"]).agg(
    total_goals = ("Player", "count"),
    total_competitions = ("Competition","nunique")

)
goals_per_competitions["goals_per_competition"] = goals_per_competitions["total_goals"]/goals_per_competitions["total_competitions"]
goals_per_competitions

                                                    total_goals  \
Player            Competition
Cristiano Ronaldo Copa del Rey                               22
                  EFL Cup                                     4
                  Europa League                               2
                  FA Cup                                     13
                  FIFA Club World Cup                         7
                  Italy Cup                                   4
                  LaLiga                                    311
                  Liga Portugal                               3
                  Premier League                            103
                  Saudi Pro League                            9
                  Serie A                                    81
                  Supercopa                                   4
                  Supercoppa Italiana                         2
                  Taca de Portugal Placard                    2
                  UEFA Champions League                     140
                  UEFA Champions League Qualifying            1
                  UEFA Super Cup                              2
Lionel Messi      Copa del Rey                               56
                  FIFA Club World Cup                         5
                  LaLiga                                    474
                  Ligue 1                                    20
                  Supercopa                                  14
                  Trophée des Champions                       2
                  UEFA Champions League                     129
                  UEFA Super Cup                              3

                                                    total_competitions  \
Player            Competition
Cristiano Ronaldo Copa del Rey                                       1
                  EFL Cup                                            1
                  Europa League                                      1
                  FA Cup                                             1
                  FIFA Club World Cup                                1
                  Italy Cup                                          1
                  LaLiga                                             1
                  Liga Portugal                                      1
                  Premier League                                     1
                  Saudi Pro League                                   1
                  Serie A                                            1
                  Supercopa                                          1
                  Supercoppa Italiana                                1
                  Taca de Portugal Placard                           1
                  UEFA Champions League                              1
                  UEFA Champions League Qualifying                   1
                  UEFA Super Cup                                     1
Lionel Messi      Copa del Rey                                       1
                  FIFA Club World Cup                                1
                  LaLiga                                             1
                  Ligue 1                                            1
                  Supercopa                                          1
                  Trophée des Champions                              1
                  UEFA Champions League                              1
                  UEFA Super Cup                                     1

                                                    goals_per_competition
Player            Competition
Cristiano Ronaldo Copa del Rey                                       22.0
                  EFL Cup                                             4.0
                  Europa League                                       2.0
                  FA Cup                                             13.0
                  FIFA Club World Cup                                 7.0
                  Italy Cup                                           4.0
                  LaLiga                                            311.0
                  Liga Portugal                                       3.0
                  Premier League                                    103.0
                  Saudi Pro League                                    9.0
                  Serie A                                            81.0
                  Supercopa                                           4.0
                  Supercoppa Italiana                                 2.0
                  Taca de Portugal Placard                            2.0
                  UEFA Champions League                             140.0
                  UEFA Champions League Qualifying                    1.0
                  UEFA Super Cup                                      2.0
Lionel Messi      Copa del Rey                                       56.0
                  FIFA Club World Cup                                 5.0
                  LaLiga                                            474.0
                  Ligue 1                                            20.0
                  Supercopa                                          14.0
                  Trophée des Champions                               2.0
                  UEFA Champions League                             129.0
                  UEFA Super Cup                                      3.0

In [ ]:
goals_per_season = df.groupby(["Player", "Season"]) .agg(
    total_goals = ("Player", "count"),
    total_seasons = ("Season","nunique")

)
goals_per_season["goals_per_season"] = goals_per_season["total_goals"]/goals_per_season["total_seasons"]
goals_per_season

                          total_goals  total_seasons  goals_per_season
Player            Season
Cristiano Ronaldo 02/03             5              1               5.0
                  03/04             6              1               6.0
                  04/05             9              1               9.0
                  05/06            12              1              12.0
                  06/07            23              1              23.0
                  07/08            42              1              42.0
                  08/09            26              1              26.0
                  09/10            33              1              33.0
                  10/11            53              1              53.0
                  11/12            60              1              60.0
                  12/13            55              1              55.0
                  13/14            51              1              51.0
                  14/15            61              1              61.0
                  15/16            51              1              51.0
                  16/17            42              1              42.0
                  17/18            44              1              44.0
                  18/19            28              1              28.0
                  19/20            37              1              37.0
                  20/21            36              1              36.0
                  21/22            24              1              24.0
                  22/23            12              1              12.0
Lionel Messi      04/05             1              1               1.0
                  05/06             8              1               8.0
                  06/07            17              1              17.0
                  07/08            16              1              16.0
                  08/09            38              1              38.0
                  09/10            47              1              47.0
                  10/11            53              1              53.0
                  11/12            73              1              73.0
                  12/13            60              1              60.0
                  13/14            41              1              41.0
                  14/15            58              1              58.0
                  15/16            41              1              41.0
                  16/17            54              1              54.0
                  17/18            45              1              45.0
                  18/19            51              1              51.0
                  19/20            31              1              31.0
                  20/21            38              1              38.0
                  21/22            14              1              14.0
                  22/23            17              1              17.0

- How many unique values are in the venue column? Which ones are they?
- Does any of the need cleaning?
- What is the distribution of home and away goals for each of the players?
- What is the scoring rate for each of the players at home and away?
- What is the distribution of goals scored by both players per day of the week?
- What is the distribution of goals scored by both of the players per month?

In [ ]:
df["Venue"].unique()

array(['H', 'A'], dtype=object)

In [ ]:
len(df["Venue"].unique())

2

NO.

In [ ]:
df.groupby(["Player", "Venue"])["Player"].count()

Player             Venue
Cristiano Ronaldo  A        306
                   H        404
Lionel Messi       A        284
                   H        419
Name: Player, dtype: int64

In [ ]:
goals_per_venue = df.groupby(["Player", "Venue"]) .agg(
    total_goals = ("Player", "count"),
    total_games= ("Date","nunique")

)
goals_per_venue["goals_per_venue"] = goals_per_venue["total_goals"]/goals_per_venue["total_games"]
goals_per_venue

                         total_goals  total_games  goals_per_venue
Player            Venue
Cristiano Ronaldo A              306          213         1.436620
                  H              404          255         1.584314
Lionel Messi      A              284          190         1.494737
                  H              419          264         1.587121

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1413 entries, 0 to 1412
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Player            1413 non-null   object
 1   Season            1413 non-null   object
 2   Competition       1413 non-null   object
 3   Matchday          1413 non-null   object
 4   Date              1413 non-null   object
 5   Venue             1413 non-null   object
 6   Club              1413 non-null   object
 7   Opponent          1413 non-null   object
 8   Result            1413 non-null   object
 9   Playing_Position  1355 non-null   object
 10  Minute            1413 non-null   object
 11  At_score          1413 non-null   object
 12  Type              1397 non-null   object
 13  Goal_assist       953 non-null    object
dtypes: object(14)
memory usage: 154.7+ KB

In [ ]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1413 entries, 0 to 1412
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Player            1413 non-null   object
 1   Season            1413 non-null   object
 2   Competition       1413 non-null   object
 3   Matchday          1413 non-null   object
 4   Date              1413 non-null   datetime64[ns]
 5   Venue             1413 non-null   object
 6   Club              1413 non-null   object
 7   Opponent          1413 non-null   object
 8   Result            1413 non-null   object
 9   Playing_Position  1355 non-null   object
 10  Minute            1413 non-null   object
 11  At_score          1413 non-null   object
 12  Type              1397 non-null   object
 13  Goal_assist       953 non-null    object
dtypes: datetime64[ns](1), object(13)
memory usage: 154.7+ KB

In [ ]:
df["day_name"] = df["Date"].dt.day_name()

df["day_name"].value_counts()

day_name
Saturday     515
Sunday       371
Wednesday    249
Tuesday      194
Thursday      45
Monday        27
Friday        12
Name: count, dtype: int64

In [ ]:
df["month"] = df["Date"].dt.month_name()
df["month"].value_counts()

month
January      171
March        171
February     160
April        149
September    149
December     142
November     135
October      133
May          123
August        56
June          12
July          12
Name: count, dtype: int64

- What is the scoring rate for each of the players per day of the week?
- What is the scoring rate for each of the players per month?

In [ ]:
goals_per_day_of_week = df.groupby(["day_name", "Player"]) .agg(
    total_goals = ("Player", "count"),
    total_games= ("Date","nunique")

)
goals_per_day_of_week["goals_per_day_of_week"] = goals_per_day_of_week["total_goals"]/goals_per_day_of_week["total_games"]
goals_per_day_of_week.sort_values("goals_per_day_of_week", ascending=False)

                             total_goals  total_games  goals_per_day_of_week
day_name  Player
Tuesday   Lionel Messi                87           52               1.673077
          Cristiano Ronaldo          107           65               1.646154
Monday    Cristiano Ronaldo           21           13               1.615385
Sunday    Cristiano Ronaldo          167          104               1.605769
          Lionel Messi               204          131               1.557252
Saturday  Lionel Messi               252          162               1.555556
          Cristiano Ronaldo          263          175               1.502857
Wednesday Lionel Messi               129           86               1.500000
Monday    Lionel Messi                 6            4               1.500000
Thursday  Cristiano Ronaldo           23           16               1.437500
          Lionel Messi                22           16               1.375000
Wednesday Cristiano Ronaldo          120           88               1.363636
Friday    Cristiano Ronaldo            9            7               1.285714
          Lionel Messi                 3            3               1.000000

In [ ]:
goals_per_month = df.groupby(["month", "Player"]) .agg(
    total_goals = ("Player", "count"),
    total_games= ("Date","nunique")

)
goals_per_month["goals_per_month"] = goals_per_month["total_goals"]/goals_per_month["total_games"]
goals_per_month.sort_values(by = "goals_per_month", ascending=False)

                             total_goals  total_games  goals_per_month
month     Player
September Lionel Messi                73           42         1.738095
March     Lionel Messi                92           55         1.672727
August    Lionel Messi                40           24         1.666667
July      Lionel Messi                 5            3         1.666667
May       Cristiano Ronaldo           68           42         1.619048
          Lionel Messi                55           34         1.617647
September Cristiano Ronaldo           76           47         1.617021
October   Cristiano Ronaldo           72           46         1.565217
February  Cristiano Ronaldo           78           51         1.529412
January   Cristiano Ronaldo           78           51         1.529412
April     Lionel Messi                70           46         1.521739
November  Cristiano Ronaldo           65           43         1.511628
December  Cristiano Ronaldo           87           58         1.500000
January   Lionel Messi                93           62         1.500000
March     Cristiano Ronaldo           79           53         1.490566
December  Lionel Messi                55           37         1.486486
February  Lionel Messi                82           56         1.464286
November  Lionel Messi                70           48         1.458333
October   Lionel Messi                61           42         1.452381
April     Cristiano Ronaldo           79           56         1.410714
June      Lionel Messi                 7            5         1.400000
July      Cristiano Ronaldo            7            5         1.400000
August    Cristiano Ronaldo           16           12         1.333333
June      Cristiano Ronaldo            5            4         1.250000

- How many clubs has each of the players played for?
- How many goals have each of the players scored in each of the teams they have played for?
- What is the scoring rate for each of the players for each of the teams?
- How many unique teams has each of the playes scored aganist?
- Which are the top 5 teams that each of the players has scored the most goals aganist?
- Which are the unique positions in the dataset? is there any that needs cleaning? if so clean it.
- Show the distribution of playong positions for each of the players

- Clean the minute column:
  1. We need to address the added time eg 90+5 to 95
  2. Change the datatype to integer
  3. Get the distribution of goals per minute for players

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1413 entries, 0 to 1412
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Player            1413 non-null   object
 1   Season            1413 non-null   object
 2   Competition       1413 non-null   object
 3   Matchday          1413 non-null   object
 4   Date              1413 non-null   datetime64[ns]
 5   Venue             1413 non-null   object
 6   Club              1413 non-null   object
 7   Opponent          1413 non-null   object
 8   Result            1413 non-null   object
 9   Playing_Position  1355 non-null   object
 10  Minute            1413 non-null   object
 11  At_score          1413 non-null   object
 12  Type              1397 non-null   object
 13  Goal_assist       953 non-null    object
 14  day_name          1413 non-null   object
 15  month             1413 non-null   object
dtypes: datetime64[ns](1), object(15)
memory usage: 176.8+ KB

In [ ]:
df.groupby("Player")["Club"].nunique()

Player
Cristiano Ronaldo    5
Lionel Messi         2
Name: Club, dtype: int64

In [ ]:
df.groupby(["Player", "Club"])["Player"].count()

Player             Club
Cristiano Ronaldo  Al-Nassr FC              9
                   Juventus FC            101
                   Manchester United      145
                   Real Madrid            450
                   Sporting CP              5
Lionel Messi       FC Barcelona           672
                   Paris Saint-Germain     31
Name: Player, dtype: int64

In [ ]:
goals_per_club = df.groupby(["Club", "Player"]) .agg(
    total_goals = ("Player", "count"),
    total_games= ("Date","nunique")

)
goals_per_club["goals_per_club"] = goals_per_club["total_goals"]/goals_per_club["total_games"]
goals_per_club.sort_values(by = "goals_per_club", ascending=False)

,,total_goals,total_games,goals_per_club
Club,Player,,,
Al-Nassr FC,Cristiano Ronaldo,9,4,2.250000
Real Madrid,Cristiano Ronaldo,450,274,1.642336
FC Barcelona,Lionel Messi,672,431,1.559165
Paris Saint-Germain,Lionel Messi,31,23,1.347826
Juventus FC,Cristiano Ronaldo,101,75,1.346667
Manchester United,Cristiano Ronaldo,145,111,1.306306
Sporting CP,Cristiano Ronaldo,5,4,1.250000

In [ ]:
df.groupby("Player")["Opponent"].nunique()

Player
Cristiano Ronaldo    129
Lionel Messi          97
Name: Opponent, dtype: int64

In [ ]:
df.groupby(["Player", "Opponent"])["Player"].count().sort_values(ascending=False).head(20)

Player             Opponent
Lionel Messi       Sevilla FC                38
                   Atletico de Madrid        32
                   Valencia CF               31
                   Athletic Bilbao           29
Cristiano Ronaldo  Sevilla FC                27
Lionel Messi       Real Betis Balompie       26
                   Real Madrid               26
                   CA Osasuna                25
Cristiano Ronaldo  Atletico de Madrid        25
Lionel Messi       RCD Espanyol Barcelona    25
                   Levante UD                24
Cristiano Ronaldo  Getafe CF                 23
Lionel Messi       Getafe CF                 21
Cristiano Ronaldo  FC Barcelona              20
Lionel Messi       SD Eibar                  20
Cristiano Ronaldo  Celta de Vigo             20
Lionel Messi       Deportivo de La Coruaa    20
                   Rayo Vallecano            18
                   Real Sociedad             18
Cristiano Ronaldo  Athletic Bilbao           17
Name: Player, dtype: int64

In [ ]:
df.head()

,Player,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist,day_name,month
0,Cristiano Ronaldo,02/03,Liga Portugal,6,2002-10-07,H,Sporting CP,Moreirense FC,3:00,LW,34,2:00,Solo run,NaN,Monday,October
1,Cristiano Ronaldo,02/03,Liga Portugal,6,2002-10-07,H,Sporting CP,Moreirense FC,3:00,LW,95,3:00,Header,Rui Jorge,Monday,October
2,Cristiano Ronaldo,02/03,Liga Portugal,8,2002-10-26,A,Sporting CP,Boavista FC,1:02,NaN,88,1:02,Right-footed shot,Carlos Martins,Saturday,October
3,Cristiano Ronaldo,02/03,Taca de Portugal Placard,Fourth Round,2002-11-24,H,Sporting CP,CD Estarreja,4:01,NaN,67,3:00,Left-footed shot,Cesar Prates,Sunday,November
4,Cristiano Ronaldo,02/03,Taca de Portugal Placard,Fifth Round,2002-12-18,H,Sporting CP,FC Oliveira do Hospital,8:01,NaN,13,3:00,NaN,NaN,Wednesday,December

In [ ]:
df["Playing_Position"].unique()

array(['LW', nan, 'RW', 'CF', 'SS', 'AM'], dtype=object)

Empty DataFrame
Columns: [Player, Season, Competition, Matchday, Date, Venue, Club, Opponent, Result, Playing_Position, Minute, At_score, Type, Goal_assist, day_name, month]
Index: []

In [ ]:
df.loc[df["Playing_Position"]== "LW ", "Playing_Position" ] = "LW"

In [ ]:
df.loc[df["Playing_Position"]== "RW ", "Playing_Position" ] = "RW"

In [ ]:
df.loc[df["Playing_Position"]== "AM ", "Playing_Position" ] = "AM"

In [ ]:
df.loc[df["Playing_Position"]== "CF ", "Playing_Position" ] = "CF"

In [ ]:
df.loc[df["Playing_Position"]== "ST", "Playing_Position" ] = "SS"

In [ ]:
df["Minute"].unique()

array(['34', '95', '88', '67', '13', '80', '74', '89', '60', '4', '44',
       '87', '9', '8', '54', '58', '46', '21', '76', '91', '63', '90',
       '51', '12', '68', '50', '82', '83', '75', '42', '14', '38', '45',
       '84', '59', '23', '19', '36', '73', '10', '39', '85', '47', '77',
       '28', '11', '86', '49', '29', '5', '57', '43', '62', '72', '79',
       '66', '41', '35', '81', '93', '22', '48', '70', '92', '69', '18',
       '56', '16', '53', '3', '24', '32', '26', '25', '30', '61', '78',
       '65', '31', '40', '6', '17', '55', '27', '15', '1', '2', '64',
       '110', '7', '71', '37', '20', '33', '52', '103', '94', '96', '120',
       '104', '97', '105', '109'], dtype=object)

In [ ]:
df.loc[df["Minute"]== "90+5", "Minute" ] = "95"

In [ ]:
df.loc[df["Minute"]== "90+1", "Minute" ] = "91"

In [ ]:
df.loc[df["Minute"]== "90+3", "Minute" ] = "93"

In [ ]:
df.loc[df["Minute"]== "90+2", "Minute" ] = "92"

In [ ]:
df.loc[df["Minute"]== "45+1", "Minute" ] = "46"

In [ ]:
df.loc[df["Minute"]== "45+2", "Minute" ] = "47"

In [ ]:
df.loc[df["Minute"]== "90+4", "Minute" ] = "94"

In [ ]:
df.loc[df["Minute"]== "90+6", "Minute" ] = "96"

In [ ]:
df.loc[df["Minute"]== "90+7", "Minute" ] = "97"

In [ ]:
df.loc[df["Minute"]== "45+7", "Minute" ] = "52"

In [ ]:
df.loc[df["Minute"]== "45+4", "Minute" ] = "49"

In [ ]:
df.groupby(["Player","Playing_Position"])["Player"].count()

Player             Playing_Position
Cristiano Ronaldo  CF                  212
                   LW                  361
                   RW                   79
Lionel Messi       AM                   15
                   CF                  316
                   LW                    1
                   RW                  316
                   SS                   55
Name: Player, dtype: int64

In [ ]:
#df["Minute"] = df["Minute"].astype(int)

In [ ]:
df["Minute"] = pd.to_numeric(df["Minute"], errors="coerce")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1413 entries, 0 to 1412
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Player            1413 non-null   object
 1   Season            1413 non-null   object
 2   Competition       1413 non-null   object
 3   Matchday          1413 non-null   object
 4   Date              1413 non-null   datetime64[ns]
 5   Venue             1413 non-null   object
 6   Club              1413 non-null   object
 7   Opponent          1413 non-null   object
 8   Result            1413 non-null   object
 9   Playing_Position  1355 non-null   object
 10  Minute            1413 non-null   int64
 11  At_score          1413 non-null   object
 12  Type              1397 non-null   object
 13  Goal_assist       953 non-null    object
 14  day_name          1413 non-null   object
 15  month             1413 non-null   object
dtypes: datetime64[ns](1), int64(1), object(14)
memory usage: 176.8+ KB

In [ ]:
df.groupby("Player")["Minute"].value_counts().sort_values(ascending=False).head(50)

Player             Minute
Cristiano Ronaldo  90        17
                   23        15
                   45        15
                   89        15
                   70        14
                   76        14
Lionel Messi       55        14
                   86        13
                   87        13
                   78        13
Cristiano Ronaldo  26        12
                   81        12
Lionel Messi       45        12
                   75        12
                   90        12
                   80        12
Cristiano Ronaldo  82        12
                   25        11
                   49        11
                   64        11
                   78        11
Lionel Messi       63        11
                   38        11
                   58        11
                   82        11
                   42        11
                   23        10
                   16        10
Cristiano Ronaldo  68        10
                   10        10
                   13        10
                   35        10
                   38        10
                   59        10
                   62        10
                   65        10
Lionel Messi       25        10
                   91        10
                   31        10
                   43        10
                   51        10
                   59        10
                   73        10
                   85        10
                   92        10
                   74        10
                   28         9
                   61         9
                   18         9
                   33         9
Name: count, dtype: int64

In [ ]:
ronaldo_df = df[df["Player"]=="Cristiano Ronaldo"]
ronaldo_real = ronaldo_df[ronaldo_df["Club"]=="Real Madrid"]
ronaldo_real[ronaldo_df["Opponent"]=="FC Barcelona"].head()

/tmp/ipython-input-47-1375541623.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ronaldo_real[ronaldo_df["Opponent"]=="FC Barcelona"].head()

,Player,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist,day_name,month
372,Cristiano Ronaldo,10/11,LaLiga,32,2011-04-16,H,Real Madrid,FC Barcelona,1:01,LW,82,1:01,Penalty,NaN,Saturday,April
373,Cristiano Ronaldo,10/11,Copa del Rey,Final,2011-04-20,A,Real Madrid,FC Barcelona,0:1 AET,CF,103,0:01,Header,Angel Di Maria,Wednesday,April
392,Cristiano Ronaldo,11/12,Supercopa,final,2011-08-17,A,Real Madrid,FC Barcelona,3:02,LW,20,1:01,Right-footed shot,Karim Benzema,Wednesday,August
448,Cristiano Ronaldo,11/12,Copa del Rey,Quarter-Finals,2012-01-18,H,Real Madrid,FC Barcelona,1:02,LW,11,1:00,Left-footed shot,Karim Benzema,Wednesday,January
454,Cristiano Ronaldo,11/12,Copa del Rey,Quarter-Finals,2012-01-25,A,Real Madrid,FC Barcelona,2:02,LW,68,2:01,Right-footed shot,Mesut Ozil,Wednesday,January

In [ ]:
#messi_df = df[df["Player"]=="Lionel Messi"]
#messi_barca = messi_df[messi_df["Club"]=="FC Barcelona"]
#messi_barca_vs_real = messi_barca[messi_df["Opponent"]=="Real Madrid"].head
#messi_barca_vs_real_fin =

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1413 entries, 0 to 1412
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Player            1413 non-null   object
 1   Season            1413 non-null   object
 2   Competition       1413 non-null   object
 3   Matchday          1413 non-null   object
 4   Date              1413 non-null   datetime64[ns]
 5   Venue             1413 non-null   object
 6   Club              1413 non-null   object
 7   Opponent          1413 non-null   object
 8   Result            1413 non-null   object
 9   Playing_Position  1355 non-null   object
 10  Minute            1413 non-null   int64
 11  At_score          1413 non-null   object
 12  Type              1397 non-null   object
 13  Goal_assist       953 non-null    object
 14  day_name          1413 non-null   object
 15  month             1413 non-null   object
dtypes: datetime64[ns](1), int64(1), object(14)
memory usage: 176.8+ KB

- Get the distribution of types ofgoals each of the players has scored
- Get the top 3 assisters for each of the players

In [ ]:
df.groupby(["Type", "Player"])["Type"].value_counts()

Type                    Player
Chest                   Lionel Messi           1
Counter attack goal     Cristiano Ronaldo      6
                        Lionel Messi           1
Deflected shot on goal  Cristiano Ronaldo      2
                        Lionel Messi           2
Direct free kick        Cristiano Ronaldo     49
                        Lionel Messi          52
Header                  Cristiano Ronaldo    112
                        Lionel Messi          24
Left-footed shot        Cristiano Ronaldo    113
                        Lionel Messi         436
Long distance kick      Cristiano Ronaldo      9
                        Lionel Messi           1
Penalty                 Cristiano Ronaldo    132
                        Lionel Messi          84
Penalty rebound         Cristiano Ronaldo      3
                        Lionel Messi           3
Right-footed shot       Cristiano Ronaldo    253
                        Lionel Messi          85
Solo run                Cristiano Ronaldo      2
                        Lionel Messi           4
Tap-in                  Cristiano Ronaldo     14
                        Lionel Messi           9
Name: count, dtype: int64

In [ ]:
df.groupby(["Player","Goal_assist"])["Player"].count().sort_values(ascending=False).head(10)

Player             Goal_assist
Lionel Messi       Luis Suarez       48
Cristiano Ronaldo  Karim Benzema     44
Lionel Messi       Dani Alves        42
                   Andres Iniesta    39
                   Xavi              34
                   Neymar            30
                   Pedro             29
Cristiano Ronaldo  Gareth Bale       29
                   Mesut Ozil        26
Lionel Messi       Jordi Alba        23
Name: Player, dtype: int64